version: '3'
services:
  legacy-groups-processor:
    image: legacy-groups-processor:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - "../.nyc_output:/app/.nyc_output"
      - "../coverage:/app/coverage"
    network_mode: "host"
